In [1]:
# install numpy in python
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
# inport numpy in python
import numpy as np

# create a numpy array in python
#              0   1   2   3   4
a = np.array([21, 22, 23, 24, 25])
print(a)

[21 22 23 24 25]


In [3]:
# access elements in numpy array in python
print(a[0]) # first element
print(a[1]) # second element

21
22


In [5]:
# modify elements in numpy array in python
a[1] = 26
print(a) # first element is modified to 100

[21 26 23 24 25]


In [7]:
# cheking version of numpy in python
print(np.__version__) # print version of numpy

1.26.4


In [9]:
# create a numpy array with zeros in python
a = np.zeros((3, 4)) # 3 rows and 4 columns
print(a) # print numpy array with zeros

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
# create 2d numpy array in python
a = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]]) # 3 rows and 3 columns
print(a) # print 2d numpy array

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [13]:
# create a 3d numpy array in python
a = np.array([[[11, 12], [13, 14]], [[15, 16], [17, 18]]]) # 2 layers, 2 rows and 2 columns

print(a) # print 3d numpy array
print(a.shape) # print shape of 3d numpy array

[[[11 12]
  [13 14]]

 [[15 16]
  [17 18]]]
(2, 2, 2)


In [15]:
# check the demensions of numpy array in python
print(a.ndim) # print number of dimensions of numpy array

3


In [17]:
# Higher-Dimensional Arrays
# create a 4d numpy array in python
a = np.array([[[[11, 12], [13, 14]], [[15, 16], [17, 18]]]]) # 1 layer, 2 rows and 2 columns
print(a) # print 4d numpy array
print(a.shape) # print shape of 4d numpy array

[[[[11 12]
   [13 14]]

  [[15 16]
   [17 18]]]]
(1, 2, 2, 2)


In [19]:
# Ellipsis (…) Indexing
arr_3d = np.array([[[11, 12], [13, 14]], [[15, 16], [17, 18]]])
print(arr_3d[..., 0])  # Access the first element along the third dimension ([[1, 3], [5, 7]])

[[11 13]
 [15 17]]
